using System.Text;
using System.Text.Json;
using BurnupApi.Data;
using BurnupApi.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers().AddJsonOptions(o =>
{
    o.JsonSerializerOptions.PropertyNamingPolicy        = JsonNamingPolicy.CamelCase;
    o.JsonSerializerOptions.DefaultIgnoreCondition      = System.Text.Json.Serialization.JsonIgnoreCondition.Never;
});

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c => c.SwaggerDoc("v1", new() { Title = "Burnup PM API", Version = "v1" }));

// PostgreSQL via EF Core
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Connection string 'DefaultConnection' is not configured.");

builder.Services.AddDbContext<BurnupDbContext>(o => o.UseNpgsql(connectionString));
builder.Services.AddScoped<DataStore>();
builder.Services.AddSingleton<BurnupService>();
builder.Services.AddScoped<JwtService>();
builder.Services.AddScoped<EmailService>();
builder.Services.AddHostedService<SnapshotWorker>();

// JWT authentication — secret must be provided via Jwt:Secret (env var JWT__Secret)
var jwtSecret = builder.Configuration["Jwt:Secret"];
if (string.IsNullOrWhiteSpace(jwtSecret))
    throw new InvalidOperationException(
        "Jwt:Secret is not configured. Set the JWT__Secret environment variable.");

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(o =>
    {
        o.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer           = true,
            ValidateAudience         = true,
            ValidateLifetime         = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer              = builder.Configuration["Jwt:Issuer"]   ?? "BurnupApi",
            ValidAudience            = builder.Configuration["Jwt:Audience"] ?? "BurnupApp",
            IssuerSigningKey         = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
        };
    });

builder.Services.AddAuthorization();

builder.Services.AddCors(o =>
    o.AddDefaultPolicy(p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));

var app = builder.Build();

// Ensure schema exists and seed if empty.
// Retries with exponential back-off so the backend survives postgres starting slowly.
await using (var scope = app.Services.CreateAsyncScope())
{
    var db     = scope.ServiceProvider.GetRequiredService<BurnupDbContext>();
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();

    for (int attempt = 1; attempt <= 6; attempt++)
    {
        try
        {
            await db.Database.EnsureCreatedAsync();

            // Idempotent DDL for schema evolution (EnsureCreatedAsync is a no-op on existing DBs)
            await db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS daily_snapshots (
                    ""Id""         integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProjectId""  text NOT NULL,
                    ""Date""       date NOT NULL,
                    ""ScopeCount"" integer NOT NULL DEFAULT 0,
                    ""DoneCount""  integer NOT NULL DEFAULT 0,
                    ""ScopeDays""  double precision NOT NULL DEFAULT 0,
                    ""DoneDays""   double precision NOT NULL DEFAULT 0,
                    CONSTRAINT ""PK_daily_snapshots"" PRIMARY KEY (""Id"")
                )");
            await db.Database.ExecuteSqlRawAsync(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_daily_snapshots_ProjectId_Date""
                ON daily_snapshots (""ProjectId"", ""Date"")");

            // Auth tables
            await db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS users (
                    ""Id""           integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Email""        text NOT NULL,
                    ""PasswordHash"" text NOT NULL DEFAULT '',
                    ""Role""         text NOT NULL DEFAULT 'user',
                    ""IsActive""     boolean NOT NULL DEFAULT true,
                    ""CreatedAt""    timestamp NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_users"" PRIMARY KEY (""Id"")
                )");
            await db.Database.ExecuteSqlRawAsync(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_users_Email"" ON users (""Email"")");

            await db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS password_reset_tokens (
                    ""Id""        integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId""    integer NOT NULL,
                    ""Token""     text NOT NULL,
                    ""ExpiresAt"" timestamp NOT NULL,
                    ""Used""      boolean NOT NULL DEFAULT false,
                    CONSTRAINT ""PK_password_reset_tokens"" PRIMARY KEY (""Id"")
                )");
            await db.Database.ExecuteSqlRawAsync(@"
                CREATE INDEX IF NOT EXISTS ""IX_password_reset_tokens_Token""
                ON password_reset_tokens (""Token"")");

            await db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS invites (
                    ""Id""                integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Token""             text NOT NULL,
                    ""Email""             text,
                    ""ExpiresAt""         timestamp NOT NULL,
                    ""Used""              boolean NOT NULL DEFAULT false,
                    ""CreatedByUserId""   integer NOT NULL,
                    CONSTRAINT ""PK_invites"" PRIMARY KEY (""Id"")
                )");
            await db.Database.ExecuteSqlRawAsync(@"
                CREATE INDEX IF NOT EXISTS ""IX_invites_Token"" ON invites (""Token"")");

            await db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS app_config (
                    ""Key""   text NOT NULL,
                    ""Value"" text NOT NULL,
                    CONSTRAINT ""PK_app_config"" PRIMARY KEY (""Key"")
                )");

            // Add UserId / PublicToken columns to projects if not present
            await db.Database.ExecuteSqlRawAsync(@"
                ALTER TABLE projects ADD COLUMN IF NOT EXISTS ""UserId"" integer");
            await db.Database.ExecuteSqlRawAsync(@"
                ALTER TABLE projects ADD COLUMN IF NOT EXISTS ""PublicToken"" text");

            await db.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS project_shares (
                    ""Id""        integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProjectId"" text NOT NULL,
                    ""UserId""    integer NOT NULL,
                    ""Role""      text NOT NULL DEFAULT 'viewer',
                    ""CreatedAt"" timestamp NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_project_shares"" PRIMARY KEY (""Id"")
                )");
            await db.Database.ExecuteSqlRawAsync(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_project_shares_ProjectId_UserId""
                ON project_shares (""ProjectId"", ""UserId"")");

            var seeder = new DatabaseSeeder(
                db,
                scope.ServiceProvider.GetRequiredService<ILogger<DatabaseSeeder>>());
            await seeder.SeedAsync();
            logger.LogInformation("Database ready.");
            break;
        }
        catch (Exception ex) when (attempt < 6)
        {
            var delay = TimeSpan.FromSeconds(Math.Pow(2, attempt - 1));
            logger.LogWarning("Database not ready (attempt {Attempt}): {Message}. Retrying in {Delay}s…",
                attempt, ex.Message, delay.TotalSeconds);
            await Task.Delay(delay);
        }
    }
}

app.UseCors();
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Burnup PM API v1"));
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.MapGet("/health", () => Results.Ok());

app.Run();
